feat: update release script

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -3,50 +3,105 @@ name: Release
 on:
   workflow_dispatch:
     inputs:
-      bump:
-        description: 'Bump'
+      version:
+        description: 'Version'
         required: true
-        default: 'patch'
-        type: choice
-        options:
-          - patch
-          - minor
+        type: string
 
 jobs:
   release:
     permissions:
       contents: write
       id-token: write
+    env:
+      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+      NPM_CONFIG_PROVENANCE: true
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout
+        uses: actions/checkout@v4
         with:
           fetch-depth: 0 # Fetches all history for all branches and tags
-      - uses: actions/setup-node@v4
+
+      - name: Setup node
+        uses: actions/setup-node@v4
         with:
           node-version: lts/*
           cache: 'npm'
           registry-url: 'https://registry.npmjs.org'
-      - run: npm ci
-      - run: |
+
+      - name: Install
+        run: npm ci
+
+      - name: Pre-flight
+        run: |
+          # Check incoming version is at or above the currently published version on NPM
+          # Note: we allow the current version in the even that a publish partially fails
+          npx semver ${{ inputs.version }} -r ">=$(npm show sanity version) 3.x"
+
+          # Check if `NODE_AUTH_TOKEN` is working
+          npm whoami
+
+          # Configure git
           # https://github.com/actions/checkout/pull/1184
           git config --global user.name 'github-actions[bot]'
           git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
 
-          npm whoami
+          # Fetch all branches (-u allows fetching the current branch)
+          git fetch origin current:current -u
+          git fetch origin next:next -u
+          git fetch origin ${{ github.ref }}:${{ github.ref }} -u
 
-          git fetch --all
+          # Check for unexpected commits in 'next'
+          git log next..current --oneline | grep -q '.' && { \
+            echo "Error: 'current' has commits that 'next' does not. Aborting."; \
+            exit 1; } || true
+
+          # Check for unexpected commits in selected branch
+          git log ${{ github.ref }}..current --oneline | grep -q '.' && { \
+            echo "Error: 'current' has commits that '${{ github.ref }}' does not. Aborting."; \
+            exit 1; } || true
+
+      - name: Rebase 'current'
+        run: |
           git checkout current
           git rebase ${{ github.ref }}
 
-          npm run build
-          lerna publish --no-private --exact --force-publish --yes $BUMP
+      - name: Version
+        run: |
+          # Just bump the versions first, no push yet
+          lerna version           \
+            --no-private          \
+            --no-git-tag-version  \
+            --no-push             \
+            --force-publish       \
+            --exact               \
+            --yes                 \
+            ${{ inputs.version }}
 
-          git push --force-with-lease
+      - name: Build
+        run: npm run build
+
+      - name: Publish
+        run: |
+          # Re-run lerna version and push since the build was successful
+          lerna version           \
+            --no-private          \
+            --force-git-tag       \
+            --force-publish       \
+            --exact               \
+            --yes                 \
+            ${{ inputs.version }}
+
+          # https://github.com/lerna/lerna/tree/v8.1.2/libs/commands/publish#bump-from-package
+          lerna publish           \
+            --force-publish       \
+            --exact               \
+            --yes                 \
+            from-package
+
+      - name: Rebase 'next'
+        run: |
           git checkout next
           git rebase current
-          git push --force-with-lease
-        env:
-          BUMP: ${{ github.event.inputs.bump }}
-          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
-          NPM_CONFIG_PROVENANCE: true
+          git push
